// src/lib/audit/actions.ts

export const AuditAction = {
  // Patient Management
  PATIENT_CREATE: "PATIENT_CREATE",
  PATIENT_UPDATE: "PATIENT_UPDATE",
  PATIENT_DELETE: "PATIENT_DELETE",
  PATIENT_PRINT: "PATIENT_PRINT",
  PATIENT_PDF_EXPORT: "PATIENT_PDF_EXPORT",
  ODONTOGRAM_CREATE: "ODONTOGRAM_CREATE",
  ODONTOGRAM_UPDATE: "ODONTOGRAM_UPDATE",
  // Agenda / Citas
  CITA_CREATE: "CITA_CREATE",
  CITA_CANCEL: "CITA_CANCEL",
  CITA_REPROGRAMAR: "CITA_REPROGRAMAR",
  CITA_REPROGRAMAR_OVERLAP: "CITA_REPROGRAMAR_OVERLAP",
  CITA_ESTADO_CHANGE: "CITA_ESTADO_CHANGE",
  CITA_TRANSITION: "CITA_TRANSITION",
  // User Management
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_ROLE_CHANGE: "USER_ROLE_CHANGE",
  USER_DEACTIVATE: "USER_DEACTIVATE",
  USER_REACTIVATE: "USER_REACTIVATE",
  USER_PASSWORD_RESET_REQUEST: "USER_PASSWORD_RESET_REQUEST",
  // Role Management
  ROLES_LIST_VIEW: "ROLES_LIST_VIEW",
  USERS_LIST_VIEW: "USERS_LIST_VIEW",
  // Professional Management
  PROFESIONAL_CREATE: "PROFESIONAL_CREATE",
  PROFESIONAL_UPDATE: "PROFESIONAL_UPDATE",
  PROFESIONAL_UPDATE_AVAILABILITY: "PROFESIONAL_UPDATE_AVAILABILITY",
  PROFESIONAL_DEACTIVATE: "PROFESIONAL_DEACTIVATE",
  PROFESIONAL_ACTIVATE: "PROFESIONAL_ACTIVATE",
  PROFESIONAL_ESPECIALIDAD_ADD: "PROFESIONAL_ESPECIALIDAD_ADD",
  PROFESIONAL_ESPECIALIDAD_REMOVE: "PROFESIONAL_ESPECIALIDAD_REMOVE",
  // Especialidad Management
  ESPECIALIDAD_CREATE: "ESPECIALIDAD_CREATE",
  ESPECIALIDAD_UPDATE: "ESPECIALIDAD_UPDATE",
  ESPECIALIDAD_DEACTIVATE: "ESPECIALIDAD_DEACTIVATE",
  ESPECIALIDAD_REACTIVATE: "ESPECIALIDAD_REACTIVATE",
  ESPECIALIDAD_DELETE: "ESPECIALIDAD_DELETE",
  ESPECIALIDAD_LIST_VIEW: "ESPECIALIDAD_LIST_VIEW",
  // Consultorio Management
  CONSULTORIO_CREATE: "CONSULTORIO_CREATE",
  CONSULTORIO_UPDATE: "CONSULTORIO_UPDATE",
  CONSULTORIO_DEACTIVATE: "CONSULTORIO_DEACTIVATE",
  CONSULTORIO_REACTIVATE: "CONSULTORIO_REACTIVATE",
  CONSULTORIO_DELETE: "CONSULTORIO_DELETE",
  // ProcedimientoCatalogo Management
  PROCEDIMIENTO_CREATE: "PROCEDIMIENTO_CREATE",
  PROCEDIMIENTO_UPDATE: "PROCEDIMIENTO_UPDATE",
  PROCEDIMIENTO_DEACTIVATE: "PROCEDIMIENTO_DEACTIVATE",
  // DiagnosisCatalog Management
  DIAGNOSIS_CATALOG_CREATE: "DIAGNOSIS_CATALOG_CREATE",
  DIAGNOSIS_CATALOG_UPDATE: "DIAGNOSIS_CATALOG_UPDATE",
  DIAGNOSIS_CATALOG_DEACTIVATE: "DIAGNOSIS_CATALOG_DEACTIVATE",
  DIAGNOSIS_CATALOG_REACTIVATE: "DIAGNOSIS_CATALOG_REACTIVATE",
  DIAGNOSIS_CATALOG_DELETE: "DIAGNOSIS_CATALOG_DELETE",
  DIAGNOSIS_CATALOG_LIST_VIEW: "DIAGNOSIS_CATALOG_LIST_VIEW",
  // AllergyCatalog Management
  ALLERGY_CATALOG_CREATE: "ALLERGY_CATALOG_CREATE",
  ALLERGY_CATALOG_UPDATE: "ALLERGY_CATALOG_UPDATE",
  ALLERGY_CATALOG_DEACTIVATE: "ALLERGY_CATALOG_DEACTIVATE",
  ALLERGY_CATALOG_REACTIVATE: "ALLERGY_CATALOG_REACTIVATE",
  ALLERGY_CATALOG_DELETE: "ALLERGY_CATALOG_DELETE",
  ALLERGY_CATALOG_LIST_VIEW: "ALLERGY_CATALOG_LIST_VIEW",
  // MedicationCatalog Management
  MEDICATION_CATALOG_CREATE: "MEDICATION_CATALOG_CREATE",
  MEDICATION_CATALOG_UPDATE: "MEDICATION_CATALOG_UPDATE",
  MEDICATION_CATALOG_DEACTIVATE: "MEDICATION_CATALOG_DEACTIVATE",
  MEDICATION_CATALOG_REACTIVATE: "MEDICATION_CATALOG_REACTIVATE",
  MEDICATION_CATALOG_DELETE: "MEDICATION_CATALOG_DELETE",
  MEDICATION_CATALOG_LIST_VIEW: "MEDICATION_CATALOG_LIST_VIEW",
  // AntecedentCatalog Management
  ANTECEDENT_CATALOG_CREATE: "ANTECEDENT_CATALOG_CREATE",
  ANTECEDENT_CATALOG_UPDATE: "ANTECEDENT_CATALOG_UPDATE",
  ANTECEDENT_CATALOG_DEACTIVATE: "ANTECEDENT_CATALOG_DEACTIVATE",
  ANTECEDENT_CATALOG_REACTIVATE: "ANTECEDENT_CATALOG_REACTIVATE",
  ANTECEDENT_CATALOG_DELETE: "ANTECEDENT_CATALOG_DELETE",
  ANTECEDENT_CATALOG_LIST_VIEW: "ANTECEDENT_CATALOG_LIST_VIEW",
  // AnamnesisConfig Management
  CONFIG_CREATE: "CONFIG_CREATE",
  CONFIG_UPDATE: "CONFIG_UPDATE",
  // Patient Diagnosis Management
  DIAGNOSIS_CREATE: "DIAGNOSIS_CREATE",
  DIAGNOSIS_UPDATE: "DIAGNOSIS_UPDATE",
  DIAGNOSIS_STATUS_CHANGE: "DIAGNOSIS_STATUS_CHANGE",
  DIAGNOSIS_DELETE: "DIAGNOSIS_DELETE",
  DIAGNOSIS_RESOLVE: "DIAGNOSIS_RESOLVE",
  DIAGNOSIS_DISCARD: "DIAGNOSIS_DISCARD",
  // Attachment Operations
  ADJUNTO_CREATE: "ADJUNTO_CREATE",
  ADJUNTO_DELETE: "ADJUNTO_DELETE",
  ADJUNTO_VIEW: "ADJUNTO_VIEW",
  ADJUNTO_DOWNLOAD: "ADJUNTO_DOWNLOAD",
  // Consent Operations
  CONSENTIMIENTO_CREATE: "CONSENTIMIENTO_CREATE",
  CONSENTIMIENTO_REVOKE: "CONSENTIMIENTO_REVOKE",
  CONSENTIMIENTO_UPDATE: "CONSENTIMIENTO_UPDATE",
  CONSENTIMIENTO_VIEW: "CONSENTIMIENTO_VIEW",
  CONSENTIMIENTO_DOWNLOAD: "CONSENTIMIENTO_DOWNLOAD",
  // Anamnesis Operations
  ANAMNESIS_CREATE: "ANAMNESIS_CREATE",
  ANAMNESIS_UPDATE: "ANAMNESIS_UPDATE",
  ANAMNESIS_DELETE: "ANAMNESIS_DELETE",
  ANAMNESIS_VIEW: "ANAMNESIS_VIEW",
  ANAMNESIS_RESTORE: "ANAMNESIS_RESTORE",
  ANAMNESIS_EXPORT: "ANAMNESIS_EXPORT",
  ANAMNESIS_PRINT: "ANAMNESIS_PRINT",
  // Report Operations
  REPORT_GENERATE: "REPORT_GENERATE",
  REPORT_GENERATE_FAILED: "REPORT_GENERATE_FAILED",
  REPORT_EXPORT_PDF: "REPORT_EXPORT_PDF",
  REPORT_EXPORT_CSV: "REPORT_EXPORT_CSV",
  REPORT_PRINT: "REPORT_PRINT",
  // Treatment Plan Operations
  TREATMENT_PLAN_CREATE: "TREATMENT_PLAN_CREATE",
  TREATMENT_PLAN_UPDATE: "TREATMENT_PLAN_UPDATE",
  TREATMENT_PLAN_STATUS_CHANGE: "TREATMENT_PLAN_STATUS_CHANGE",
  TREATMENT_PLAN_COMPLETE: "TREATMENT_PLAN_COMPLETE",
  TREATMENT_PLAN_CANCEL: "TREATMENT_PLAN_CANCEL",
  TREATMENT_PLAN_REACTIVATE: "TREATMENT_PLAN_REACTIVATE",
  // Treatment Step Operations
  TREATMENT_STEP_CREATE: "TREATMENT_STEP_CREATE",
  TREATMENT_STEP_UPDATE: "TREATMENT_STEP_UPDATE",
  TREATMENT_STEP_DELETE: "TREATMENT_STEP_DELETE",
  TREATMENT_STEP_STATUS_CHANGE: "TREATMENT_STEP_STATUS_CHANGE",
  TREATMENT_STEP_SESSION_COMPLETE: "TREATMENT_STEP_SESSION_COMPLETE",
  // TreatmentPlanCatalog Management
  TREATMENT_PLAN_CATALOG_CREATE: "TREATMENT_PLAN_CATALOG_CREATE",
  TREATMENT_PLAN_CATALOG_UPDATE: "TREATMENT_PLAN_CATALOG_UPDATE",
  TREATMENT_PLAN_CATALOG_DEACTIVATE: "TREATMENT_PLAN_CATALOG_DEACTIVATE",
  TREATMENT_PLAN_CATALOG_REACTIVATE: "TREATMENT_PLAN_CATALOG_REACTIVATE",
  TREATMENT_PLAN_CATALOG_DELETE: "TREATMENT_PLAN_CATALOG_DELETE",
  // — futuras acciones comunes —
  // PATIENT_VIEW: "PATIENT_VIEW",
  // USER_LOGIN: "USER_LOGIN",
} as const
export type AuditAction = typeof AuditAction[keyof typeof AuditAction]

// Mantener las entidades "de negocio" coherentes
export const AuditEntity = {
  Patient: "Patient",
  Appointment: "Appointment",
  Cita: "Cita", // Alias en español para consistencia con modelo Prisma
  User: "User",
  Usuario: "Usuario", // Alias en español para consistencia con modelo Prisma
  Rol: "Rol",
  Profesional: "Profesional",
  OdontogramSnapshot: "OdontogramSnapshot",
  Especialidad: "Especialidad",
  Consultorio: "Consultorio",
  ProcedimientoCatalogo: "ProcedimientoCatalogo",
  DiagnosisCatalog: "DiagnosisCatalog",
  AllergyCatalog: "AllergyCatalog",
  MedicationCatalog: "MedicationCatalog",
  AntecedentCatalog: "AntecedentCatalog",
  AnamnesisConfig: "AnamnesisConfig",
  PatientDiagnosis: "PatientDiagnosis",
  // Attachment and Consent Entities
  Adjunto: "Adjunto",
  Consentimiento: "Consentimiento",
  // Anamnesis Entity
  PatientAnamnesis: "PatientAnamnesis",
  Anamnesis: "Anamnesis", // Alias en español
  // Report Entity
  Report: "Report",
  // Treatment Plan Entities
  TreatmentPlan: "TreatmentPlan",
  TreatmentStep: "TreatmentStep",
  TreatmentPlanCatalog: "TreatmentPlanCatalog",
  // agrega las que necesites
} as const
export type AuditEntity = typeof AuditEntity[keyof typeof AuditEntity]
